import type { Metadata } from "next";
import "./globals.css";
import {
  dmSansBold,
  dmSansBoldItalic,
  dmSansItalic,
  dmSansMedium,
  dmSansMediumItalic,
  dmSansRegular,
  dmSansSemiBold,
  interBold,
  interBoldItalic,
  interItalic,
  interLight,
  interMedium,
  interMediumItalic,
  interRegular,
  interSemiBold,
} from "@/lib/config/fonts";
import Nav from "@/components/ui/Nav";
import Footer from "@/components/ui/Footer";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Erprex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://cdn.weglot.com/weglot.min.js"
          strategy="beforeInteractive"
        />
        <Script id="weglot-init" strategy="beforeInteractive">
          {`
            Weglot.initialize({
              api_key: 'wg_839bfed9490cac911d56621ecfd1a1217'
            });
          `}
        </Script>
      </head>
      <body
        className={`${dmSansBold.variable} ${dmSansBoldItalic.variable} ${dmSansItalic.variable} ${dmSansMedium.variable} ${dmSansMediumItalic.variable} ${dmSansRegular.variable} ${dmSansSemiBold.variable} ${interBold.variable} ${interBoldItalic.variable} ${interItalic.variable} ${interLight.variable} ${interMedium.variable} ${interMediumItalic.variable} ${interRegular.variable} ${interSemiBold.variable} antialiased bg-my-bg `}
      >
        <Nav />
        <main className="font-[family-name:var(--font-inter-regular)] min-h-screen">
          {children}
        </main>
        <Footer />
        <div id="portal-root" />
      </body>
    </html>
  );
}
