import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  dmSansBold,
  dmSansBoldItalic,
  dmSansItalic,
  dmSansMedium,
  dmSansMediumItalic,
  dmSansRegular,
  dmSansSemiBold,
  interBold,
  interBoldItalic,
  interItalic,
  interLight,
  interMedium,
  interMediumItalic,
  interRegular,
  interSemiBold,
} from "@/lib/configs/fonts";

export const metadata: Metadata = {
  title: "Erprex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSansBold.variable} ${dmSansBoldItalic.variable} ${dmSansItalic.variable} ${dmSansMedium.variable} ${dmSansMediumItalic.variable} ${dmSansRegular.variable} ${dmSansSemiBold.variable} ${interBold.variable} ${interBoldItalic.variable} ${interItalic.variable} ${interLight.variable} ${interMedium.variable} ${interMediumItalic.variable} ${interRegular.variable} ${interSemiBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
